#!/bin/sh


CURDIR=$(cd $(dirname $0) && pwd)
CONFIDR="$CURDIR/conf"

PACKAGEID="com.modouwifi.vpnssh"


# to tp

TO_TP_TITLE="SSH-VPN"
TO_TP_CONF_DIR="/data/conf/launcher/conf.d"
TO_TP_CONF_FILE=$TO_TP_CONF_DIR/ssh.conf

TO_TP_ICON="$CURDIR/res/icon.png"
TO_TP_PRESSED_ICON="$CURDIR/res/picon.png"

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURDIR/lib

usage()
{
	echo "ERROR: action missing"
	echo "syntax: $0 <start|stop|restart|status|config|install|uninstall>"
	echo "example: $0 start"
}

install()
{
	#to tp
	if [! -d $TO_TP_CONF_DIR ];then
		mkdir -p $TO_TP_CONF_DIR
	fi

	echo "{" > "$TO_TP_CONF_FILE"
	echo "\"name]\" : \"$TO_TP_TITLE\"," >> "$TO_TP_CONF_FILE"
    echo "\"icon\" : \"$TO_TP_ICON\"," >> "$TO_TP_CONF_FILE"
	echo "\"iconPressed\" : \"$TO_TP_PRESSED_ICON\"," >> "$TO_TP_CONF_FILE"
	echo "\"exec\" : \"$CURDIR/sbin/ssh.sh \"," >> "$TO_TP_CONF_FILE"
	echo "\"msgNum\" : 4" >> "$TO_TP_CONF_FILE"
	echo "}" >> "$TO_TP_CONF_FILE"

    /system/sbin/appInfo.sh set_status $PACKAGEID NOTRUNNING	
	return 0;
}

uninstall() 
{
    rm $TO_TP_CONF_FILE	
	echo "uninstall"
	return 0
} 
stop()
{
    /system/sbin/appInfo.sh set_status $PACKAGEID NOTRUNNING 
	return 0; 
}

start()
{
   $CURDIR/sbin/ssh.sh 
   /system/sbin/appInfo.sh set_status $PACAKGEID ISRUNNING

   return 0;

}



status()
{

	echo "Hello,modou";
	return 0;
}

set_config()
{
    #remain to be config

}


#main
if [ $# -lt 1 ];then
		usage init
		exit 1
fi


case "$1" in
	"stop")
	    stop;
		if [ "0" != "$?" ];then
			exit 1;
		fi
		exit 0;
		;;

	"start")
		start;
		if ["0" != "$?" ];then
			exit 1;
		fi
		exit 0;
		;;
	"status")
		status;
		if ["0" != "$?" ];then
			exit 1;
		fi
		exit 0;
		;;

	"set_config")
		set_config;
		if ["0" != "$?" ];then
			exit 1;
		fi
		exit 0;
		;;
	"install")
		install;
		if ["0" != "$?"];then
			exit 1;
		fi
		exit 0;
		;;
	"uninstall")
		stop;
		uninstall;
		if ["0" != "$?"];then
			exit 1;
		fi
		;;
	*)
		usage init;
		exit 1;
		;;
esac
